# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[constraint]]
  name = "github.com/argoproj/argo"
  branch = "release-2.2"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/kube-openapi"
  branch = "release-1.10"

[[constraint]]
  name = "github.com/kubeflow/pytorch-operator"
  branch = "master"

[[constraint]]
  name = "github.com/kubeflow/tf-operator"
  branch = "master"

[[constraint]]
  name = "github.com/kubeflow/mpi-operator"
  branch = "master"

[prune]
   unused-packages = true
   go-tests = true
   non-go = true

  [[prune.project]]
    name = "github.com/argoproj/argo"
    non-go = false
    unused-packages = false
